### ISSUE TITLE
Cache buster for assets

### ISSUE THREAD

**Issue by zerok** [gograz/website#3]
Once we have an asset pipeline this should also handle cache busting of all the relevant files.

**Comment by m12r** [comment]
Hmm, Hugo provides this functionality out of the box with [Hugo Pipes](https://gohugo.io/hugo-pipes/).

Example in `themes/gograz/layouts/meetup/single.html`:

``` html
{{ if .Params.MeetupID }}
    {{ $js := resources.Get "js/meetup-rsvps.js" | minify | fingerprint }}
    <script src="{{ $js.Permalink }}" integrity="{{ $js.Data.Integrity }}"></script>
{{ end }}
```

The only one other thing I had to do, is moving the javascript from `static/js` to `themes/gograz/assets/js`. With this method the assets keep a stable name in the repository itself.

Would this be an option? Or is there a more elegant global solution in the Javascript part to this problem?

**Comment by m12r** [comment]
@zerok After merging #7, I think this issue can be closed.
